
'use strict';
const $=id=>document.getElementById(id),N=window.NF,V=window.Vex.Flow;
let state=N.demo(),history=[],audioContext=null,sourceBuffer=null,cleanedBuffer=null,scoreBuffer=null,sourceName='',sourceKind='demo',playing=false,playingOriginal=false,playNode=null,playStarted=0,playOffset=0,playRaf=0,loop=false,renderVersion=0,recording=false,requestingMic=false,recorder=null,stream=null,analyser=null,micNode=null,meterRaf=0,recordStart=0,recordTimer=null,busy=false,cancelled=false,synthJob=0,toastTimer=null,currentHighlight=-2;
const storageKey='noteflow-score-v1';
try{const saved=localStorage.getItem(storageKey);if(saved){state=N.validateProject(JSON.parse(saved));sourceKind='restored'}}catch{}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),5000)}
function time(s){s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function seconds(){return N.totalBeats(state.notes)*60/state.tempo}
function snapshot(){history.push(JSON.stringify(state));if(history.length>30)history.shift()}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(state));$('save-state').textContent=state.isDemo?'Example score · Try recording your own':'Score saved on this device'}catch{$('save-state').textContent='Download a project to keep this score'}}
function syncFields(){for(const k of ['title','instrument','sourceInstrument','tempo','meter','grid','noise','mode','sensitivity'])$(k).value=state[k]}
function invalidate(){renderVersion++;scoreBuffer=null;synthJob++;stopPlayback();playOffset=0;$('seek').value=0;$('play-time').textContent='00:00'}
function commit(){state.version=2;state.isDemo=false;invalidate();renderScore();renderEditor();persist()}
function setBusy(value,label){busy=value;if(value)synthJob++;$('progress-area').hidden=!value;$('progress-label').textContent=label||'Listening for notes…';for(const id of ['record','audio-file','demo','instrument','sourceInstrument','tempo','meter','grid','noise','mode','sensitivity','dropzone','play','source-play','edit','add-note','undo','export','open-project','retranscribe','audio-compare'])$(id).disabled=value;for(const el of $('note-rows').querySelectorAll('select,input,button'))el.disabled=value;$('title').disabled=value;if(!value){$('retranscribe').disabled=!sourceBuffer;$('audio-compare').disabled=!cleanedBuffer;$('export-cleaned').disabled=!cleanedBuffer;$('undo').disabled=history.length===0}}
async function context(){if(!audioContext)audioContext=new (window.AudioContext||window.webkitAudioContext)();await audioContext.resume();return audioContext}
function setIcon(button,name){$(button).querySelector('use')?.setAttribute('href','#i-'+name)}
function highlight(index){if(index===currentHighlight)return;currentHighlight=index;for(const el of document.querySelectorAll('.playing-note'))el.classList.remove('playing-note');if(index>=0)for(const el of document.querySelectorAll(`[data-note-index="${index}"]`))el.classList.add('playing-note')}
function renderScore(forceWidth){
 const bars=N.measures(state.notes,state.meter),spec=N.instruments[state.instrument];
 $('paper-instrument').textContent=spec.name.toUpperCase();$('paper-tempo').textContent='♩ = '+state.tempo;$('paper-key').textContent='Concert pitch · C major / A minor notation';$('paper-measures').textContent=`${bars.length} measures`;$('score-status').textContent=state.isDemo?'DEMO':'YOUR SCORE';$('play-total').textContent=time(seconds());$('clef-label').textContent=spec.description;
 $('audio-name').textContent=sourceName||state.title;$('audio-detail').textContent=sourceKind==='demo'?`Two-hand demo · ${bars.length} measures`:sourceBuffer?`${sourceKind==='recording'?'Microphone recording':'Imported audio'} · ${N.soundEvents(state.notes).length} notes`:'Saved score · Original audio not stored';$('audio-length').textContent=time(sourceBuffer?.duration||seconds());$('source-play').disabled=busy||(!sourceBuffer&&sourceKind!=='demo');$('retranscribe').disabled=busy||!sourceBuffer;$('audio-compare').disabled=busy||!cleanedBuffer;$('export-cleaned').disabled=!cleanedBuffer;
 try{NoteflowNotation.draw($('notation'),state,{width:forceWidth,onSelect:index=>{if(busy||recording)return;$('editor').hidden=false;$('edit').setAttribute('aria-expanded','true');renderEditor(index);$('editor').scrollIntoView({behavior:'smooth',block:'nearest'})}})}catch(e){console.error('Notation:',e);$('notation').textContent='The score could not be drawn. Your notes remain available in Edit notes and MusicXML.';toast('There was a notation problem. You can still edit and export your notes.')}
}
function renderEditor(selected=-1){
 if($('editor').hidden){$('undo').disabled=history.length===0;return}
 const body=$('note-rows');body.replaceChildren();state.notes.forEach((n,i)=>{const tr=document.createElement('tr');if(selected===i)tr.classList.add('selected');const number=document.createElement('td');number.textContent=String(i+1).padStart(2,'0');const ptd=document.createElement('td'),pitch=document.createElement('input');pitch.type='text';pitch.className='chord-input';pitch.setAttribute('aria-label',`Pitches for event ${i+1}`);pitch.value=N.pitches(n).map(N.noteName).join(' ')||'Rest';pitch.placeholder='C4 E4 G4';pitch.addEventListener('change',()=>{try{const ps=N.parsePitches(pitch.value);snapshot();n.pitches=ps;n.midi=ps[0]??null;n.tieFrom=(n.tieFrom||[]).filter(p=>ps.includes(p));if(state.notes[i+1])state.notes[i+1].tieFrom=(state.notes[i+1].tieFrom||[]).filter(p=>ps.includes(p));commit()}catch(e){toast(e.message);pitch.value=N.pitches(n).map(N.noteName).join(' ')||'Rest'}});ptd.append(pitch);
 const dtd=document.createElement('td'),dur=document.createElement('select');dur.setAttribute('aria-label',`Duration for note ${i+1}`);const options=[[.25,'Sixteenth · ¼ beat'],[.5,'Eighth · ½ beat'],[.75,'Dotted eighth · ¾ beat'],[1,'Quarter · 1 beat'],[1.5,'Dotted quarter · 1½ beats'],[2,'Half · 2 beats'],[3,'Dotted half · 3 beats'],[4,'Whole · 4 beats']];if(!options.some(x=>x[0]===n.beats))options.push([n.beats,`${n.beats} beats (tied)`]);options.sort((a,b)=>a[0]-b[0]);options.forEach(([v,l])=>dur.add(new Option(l,String(v))));dur.value=String(n.beats);dur.addEventListener('change',()=>{if((N.totalBeats(state.notes)-n.beats+Number(dur.value))*60/state.tempo>300){toast('Please keep edited scores under 5 minutes.');dur.value=n.beats;return}snapshot();n.beats=Number(dur.value);commit()});dtd.append(dur);
 const rtd=document.createElement('td'),remove=document.createElement('button');remove.textContent='×';remove.className='remove-note';remove.setAttribute('aria-label',`Remove note ${i+1}`);remove.disabled=state.notes.length===1;remove.addEventListener('click',()=>{snapshot();state.notes.splice(i,1);commit()});rtd.append(remove);tr.append(number,ptd,dtd,rtd);body.append(tr)});$('undo').disabled=history.length===0;
 if(selected>=0)body.children[selected]?.scrollIntoView({behavior:'smooth',block:'nearest'});
}
function drawWave(canvas,data,color='#abc292'){
 const ratio=window.devicePixelRatio||1,w=canvas.clientWidth||300,h=canvas.clientHeight||48;canvas.width=w*ratio;canvas.height=h*ratio;const c=canvas.getContext('2d');c.scale(ratio,ratio);c.clearRect(0,0,w,h);c.fillStyle=color;const count=Math.floor(w/4),step=Math.max(1,Math.floor((data?.length||0)/count));for(let i=0;i<count;i++){let amp=0;if(data){for(let j=i*step;j<Math.min((i+1)*step,data.length);j++)amp=Math.max(amp,Math.abs(data[j]));amp=Math.min(1,amp*1.3)}const height=Math.max(2,amp*(h-6));c.beginPath();c.roundRect(i*4,h/2-height/2,2,height,1);c.fill()}}
function demoWave(){const arr=new Float32Array(360);state.notes.forEach((n,i)=>{for(let j=0;j<10;j++)arr[(i*11+j)%360]=(N.pitches(n).length? .2+((N.pitches(n)[0]%12)/20):0)*Math.exp(-j/5)});return arr}
async function synthesize(project,rate=22050){
 const length=N.totalBeats(project.notes)*60/project.tempo;if(length>300)throw new Error('Please keep scores under 5 minutes.');const Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!Offline)throw new Error('Your browser does not support audio synthesis. Try Chrome or Edge.');const ctx=new Offline(1,Math.ceil((length+.3)*rate),rate);const master=ctx.createGain(),maxChord=Math.max(1,...project.notes.map(n=>N.pitches(n).length));master.gain.value=.65/Math.sqrt(maxChord);master.connect(ctx.destination);
 const sustained=['violin','viola','cello','flute','trombone'].includes(project.instrument),real=new Float32Array(8),imag=new Float32Array(project.instrument==='flute'?[0,1,.08,.02,0,0,0,0]:project.instrument==='trombone'?[0,1,.5,.3,.2,.1,.05,.02]:sustained?[0,1,.36,.2,.12,.08,.05,.03]:project.instrument==='guitar'?[0,1,.4,.22,.15,.08,.04,.02]:[0,1,.36,.12,.06,.025,.014,.007]);const wave=ctx.createPeriodicWave(real,imag);
 for(const n of N.soundEvents(project.notes)){const t=n.start*60/project.tempo,d=(n.end-n.start)*60/project.tempo,osc=ctx.createOscillator(),gain=ctx.createGain(),attack=sustained?Math.min(.05,d*.2):.006,end=t+d*.94;osc.frequency.value=440*Math.pow(2,(n.midi-69)/12);osc.setPeriodicWave(wave);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.38,t+attack);gain.gain.exponentialRampToValueAtTime(sustained?.26:.12,Math.max(t+attack+.001,end-.025));gain.gain.linearRampToValueAtTime(0,t+d+.06);osc.connect(gain).connect(master);osc.start(t);osc.stop(t+d+.08)}
 return ctx.startRendering();
}
async function ensureScore(){if(scoreBuffer)return scoreBuffer;const revision=renderVersion,buf=await synthesize(structuredClone(state));if(revision!==renderVersion)throw new Error('The score changed. Press play again.');scoreBuffer=buf;return buf}
function stopPlayback(reset=false){if(playNode){if(playing)playOffset=Math.min(seconds(),Math.max(0,audioContext.currentTime-playStarted));playNode.onended=null;try{playNode.stop()}catch{}playNode=null}playing=false;playingOriginal=false;cancelAnimationFrame(playRaf);setIcon('play','play');setIcon('source-play','play');$('play').setAttribute('aria-label','Play sheet music');$('source-play').setAttribute('aria-label','Play original audio');$('play-label').textContent='Play your score';highlight(-1);if(reset){playOffset=0;$('seek').value=0;$('play-time').textContent='00:00'}}
function tick(){if(!playing)return;const pos=Math.min(seconds(),Math.max(0,audioContext.currentTime-playStarted));$('play-time').textContent=time(pos);$('seek').value=String(pos/Math.max(.1,seconds())*1000);let elapsed=0,index=-1;for(let i=0;i<state.notes.length;i++){const d=state.notes[i].beats*60/state.tempo;if(pos>=elapsed&&pos<elapsed+d){index=i;break}elapsed+=d}highlight(index);playRaf=requestAnimationFrame(tick)}
async function playScore(){
 if(playing){stopPlayback();return}if(busy||recording||requestingMic)return;const job=++synthJob;$('play').disabled=true;
 try{await context();stopPlayback();$('play-label').textContent='Preparing playback…';const buffer=await ensureScore();if(job!==synthJob)return;if(playOffset>=seconds()-.05)playOffset=0;playNode=audioContext.createBufferSource();playNode.buffer=buffer;const gain=audioContext.createGain();gain.gain.value=Number($('volume').value)/100;window.currentGain=gain;playNode.connect(gain).connect(audioContext.destination);playStarted=audioContext.currentTime-playOffset;playNode.start(0,playOffset);playing=true;setIcon('play','pause');$('play').setAttribute('aria-label','Pause sheet music');$('play-label').textContent='Playing your score';playNode.onended=()=>{stopPlayback(true);if(loop)playScore()};tick()}catch(e){toast(e.message);$('play-label').textContent='Play your score'}finally{$('play').disabled=busy||recording}}
async function playOriginal(){if(playingOriginal){stopPlayback();return}if(busy||recording)return;const job=++synthJob;try{await context();stopPlayback();const buffer=($('audio-compare').value==='cleaned'?cleanedBuffer:sourceBuffer)||(sourceKind==='demo'?await synthesize(N.demo()):null);if(!buffer||job!==synthJob)return;playNode=audioContext.createBufferSource();playNode.buffer=buffer;const gain=audioContext.createGain();gain.gain.value=Number($('volume').value)/100;window.currentGain=gain;playNode.connect(gain).connect(audioContext.destination);playNode.start();playingOriginal=true;setIcon('source-play','pause');$('source-play').setAttribute('aria-label','Stop original audio');$('play-label').textContent=$('audio-compare').value==='cleaned'?'Playing cleaned audio':'Playing original audio';playNode.onended=()=>stopPlayback()}catch(e){toast(e.message)}}
function sourceTab(mode){if(recording||requestingMic||busy)return;for(const key of ['record','upload']){$(key+'-tab').classList.toggle('active',key===mode);$(key+'-tab').setAttribute('aria-selected',String(key===mode));$(key+'-pane').hidden=key!==mode}}
async function transcribe(buffer,name,kind){
 if(buffer.duration>120.5)throw new Error('Please choose a clip of 2 minutes or less.');if(buffer.duration<.2)throw new Error('That clip is too short. Please record a few notes.');cancelled=false;stopPlayback(true);setBusy(true,'Preparing your audio…');$('progress').value=1;
 try{
  const rate=22050,Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext,offline=new Offline(1,Math.ceil(buffer.duration*rate),rate),src=offline.createBufferSource();src.buffer=buffer;src.connect(offline.destination);src.start();const mono=await offline.startRendering();if(cancelled)throw new Error('Cancelled');
  $('progress-label').textContent=state.noise==='off'?'Preparing transcription…':'Reducing steady background noise…';const cleanup=await NoteflowNoise.reduce(mono.getChannelData(0),rate,state.noise,p=>{$('progress').value=2+Math.round(p*18)},()=>cancelled);if(cancelled)throw new Error('Cancelled');
  $('progress-label').textContent=state.mode==='poly'?'Finding notes and chords… This may take a moment.':'Following the melody…';
  const events=state.mode==='poly'?await NoteflowPoly.detect(cleanup.samples,rate,{sensitivity:state.sensitivity},p=>{$('progress').value=20+Math.round(p*78)},()=>cancelled):await N.detectEvents(cleanup.samples,rate,{instrument:state.sourceInstrument,sensitivity:state.sensitivity},p=>{$('progress').value=20+Math.round(p*78)},()=>cancelled);
  if(cancelled)throw new Error('Cancelled');if(events.length>5000)throw new Error('This clip has too many note changes. Try a shorter recording.');const notes=N.quantizePoly(events,state.tempo,state.grid);if(notes.some(n=>N.pitches(n).length>16))throw new Error('Too many overlapping sounds were detected. Try Fewer false notes or a cleaner recording.');if(notes.length>1500)throw new Error('This clip has too many note changes. Try a shorter recording.');if(!notes.some(n=>N.pitches(n).length))throw new Error('No clear notes found. Try moving closer to the microphone, using lighter noise reduction, or selecting Catch quiet notes.');
  snapshot();state.notes=notes;state.title=name.replace(/\.[^.]+$/,'').slice(0,80)||'Untitled music';state.version=2;state.isDemo=false;sourceBuffer=buffer;sourceName=name;sourceKind=kind;cleanedBuffer=audioContext.createBuffer(1,cleanup.samples.length,rate);cleanedBuffer.copyToChannel(cleanup.samples,0);$('audio-compare').value='original';invalidate();syncFields();renderScore();renderEditor();drawWave($('audio-wave'),buffer.getChannelData(0));persist();$('processing-report').hidden=false;$('processing-report').textContent=`${state.mode==='poly'?'Chord transcription':'Melody transcription'} · Noise reduction: ${state.noise} · Review the score before exporting.`;toast(`Your score is ready: ${N.soundEvents(notes).length} notes. Play it back and review the pitches.`);
 }finally{setBusy(false);$('source-play').disabled=!sourceBuffer&&sourceKind!=='demo'}
}
async function importAudio(file){if(!file||busy||recording||requestingMic)return;if(file.size>30*1024*1024){toast('Please choose an audio file smaller than 30 MB.');return}stopPlayback();setBusy(true,'Opening your recording…');try{const ctx=await context();let buffer;try{buffer=await ctx.decodeAudioData(await file.arrayBuffer())}catch{throw new Error('This audio format could not be opened. Try a WAV or MP3 file.')}await transcribe(buffer,file.name,'upload')}catch(e){toast(e.message==='Cancelled'?'Transcription cancelled. Your previous score is safe.':e.message)}finally{setBusy(false);$('source-play').disabled=!sourceBuffer&&sourceKind!=='demo';$('audio-file').value=''}}
function cleanupMic(){clearInterval(recordTimer);recordTimer=null;cancelAnimationFrame(meterRaf);stream?.getTracks().forEach(t=>t.stop());stream=null;try{micNode?.disconnect()}catch{}micNode=null;analyser=null;recording=false;requestingMic=false;document.body.classList.remove('recording');$('record-button-text').textContent='Start recording';$('record-label').textContent='Ready when you are';$('record-hint').innerHTML='Leave a short quiet pause,<br>then play your instrument.';$('timer').innerHTML='00:00 <span>/ 02:00</span>';for(const id of ['instrument','sourceInstrument','tempo','meter','grid','noise','mode','sensitivity','demo','upload-tab','record-tab','edit','export','play','source-play','open-project','title','retranscribe','audio-compare'])$(id).disabled=false;$('record').disabled=false;drawWave($('live-wave'),null);$('source-play').disabled=!sourceBuffer&&sourceKind!=='demo';$('retranscribe').disabled=!sourceBuffer;$('audio-compare').disabled=!cleanedBuffer}
function micFrame(){if(!recording||!analyser)return;const samples=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(samples);drawWave($('live-wave'),samples,'#91ad78');const elapsed=(performance.now()-recordStart)/1000;$('timer').innerHTML=time(elapsed)+' <span>/ 02:00</span>';meterRaf=requestAnimationFrame(micFrame)}
async function record(){
 if(recording){recorder?.stop();return}if(requestingMic||busy)return;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('Microphone recording isn’t available here. Open the live app in a new browser tab, or upload an audio file.');return}
 synthJob++;stopPlayback();requestingMic=true;$('record').disabled=true;$('record-button-text').textContent='Allow microphone access…';
 try{await context();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{const recordingMime=recorder.mimeType;cleanupMic();if(!chunks.length){toast('The recording was empty. Please try again.');return}setBusy(true,'Opening your recording…');try{const buffer=await audioContext.decodeAudioData(await new Blob(chunks,{type:recordingMime}).arrayBuffer());await transcribe(buffer,`My ${state.sourceInstrument==='other'?'new':state.sourceInstrument} performance`,'recording')}catch(e){toast(e.message==='Cancelled'?'Transcription cancelled. Your previous score is safe.':e.message)}finally{setBusy(false);$('source-play').disabled=!sourceBuffer&&sourceKind!=='demo'}};
 recorder.onerror=()=>{cleanupMic();toast('Recording stopped unexpectedly. Please check your microphone and try again.')};micNode=audioContext.createMediaStreamSource(stream);analyser=audioContext.createAnalyser();analyser.fftSize=1024;micNode.connect(analyser);recorder.start(250);recording=true;requestingMic=false;recordStart=performance.now();document.body.classList.add('recording');$('record').disabled=false;$('record-button-text').textContent='Stop & transcribe';$('record-label').textContent='Listening to your performance';$('record-hint').innerHTML='Pause briefly, then play.<br>Stop when your performance is complete.';for(const id of ['instrument','sourceInstrument','tempo','meter','grid','noise','mode','sensitivity','demo','upload-tab','edit','export','play','source-play','open-project','title','retranscribe','audio-compare'])$(id).disabled=true;$('editor').hidden=true;$('edit').setAttribute('aria-expanded','false');micFrame();recordTimer=setInterval(()=>{if(recording&&performance.now()-recordStart>=120000)recorder.stop()},250);
 }catch(e){cleanupMic();const messages={NotAllowedError:'Microphone access was denied. Allow it in your browser’s site settings, or use Upload audio.',NotFoundError:'No microphone was found. Connect one, or upload an audio file.',NotReadableError:'Your microphone is busy. Close other recording apps and try again.'};toast(messages[e.name]||'The microphone could not start. Try uploading a recording instead.')}
}
function download(bytes,filename,type){const url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function filename(){return (state.title||'My melody').replace(/[^\p{L}\p{N}\-_ ]/gu,'').trim().slice(0,65)||'My melody'}
async function exportPDF(){
 stopPlayback();renderScore(760);const svgs=[...$('notation').querySelectorAll('svg')].map(s=>s.cloneNode(true));renderScore();if(!svgs.length)throw new Error('No rendered score is available. Try MusicXML instead.');const doc=await PDFLib.PDFDocument.create();doc.setTitle(state.title);doc.setCreator('Noteflow');const font=await doc.embedFont(PDFLib.StandardFonts.Helvetica),titleFont=await doc.embedFont(PDFLib.StandardFonts.TimesRoman);const safe=s=>String(s).replace(/[^\x20-\x7e]/g,'');let page,y=0,pageNo=0;
 const newPage=()=>{page=doc.addPage([595.28,841.89]);pageNo++;y=756;const title=safe(state.title)||'My melody';const size=Math.min(22,500/titleFont.widthOfTextAtSize(title,22)*22);page.drawText(title,{x:Math.max(40,(595.28-titleFont.widthOfTextAtSize(title,size))/2),y:790,size,font:titleFont,color:PDFLib.rgb(.15,.2,.15)});page.drawText(`${safe(state.instrument.toUpperCase())}  |  Quarter note = ${state.tempo}  |  ${state.meter}  |  Concert pitch`,{x:44,y:764,size:9,font});page.drawText(`Created with Noteflow  |  ${pageNo}`,{x:44,y:30,size:8,font,color:PDFLib.rgb(.5,.55,.47)})};newPage();
 for(const svg of svgs){const clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const box=clone.getAttribute('viewBox').split(' ').map(Number),rasterHeight=Math.ceil(1520*box[3]/box[2]);clone.setAttribute('width','1520');clone.setAttribute('height',String(rasterHeight));clone.querySelectorAll('.playing-note').forEach(e=>e.classList.remove('playing-note'));const xml=new XMLSerializer().serializeToString(clone),url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml;charset=utf-8'}));let img;try{img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Could not prepare the PDF. Use your browser’s Print menu instead.'));i.src=url})}finally{URL.revokeObjectURL(url)}const canvas=document.createElement('canvas');canvas.width=1520;canvas.height=rasterHeight;const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,1520,rasterHeight);ctx.drawImage(img,0,0);const png=await doc.embedPng(canvas.toDataURL('image/png'));const h=511.28*box[3]/box[2];if(y-h<50)newPage();y-=h;page.drawImage(png,{x:42,y,width:511.28,height:h});}
 download(await doc.save(),filename()+'.pdf','application/pdf');
}
async function doExport(format,button){if(busy||recording)return;button.disabled=true;try{if(format==='pdf')await exportPDF();if(format==='midi')download(N.midiFile(state),filename()+'.mid','audio/midi');if(format==='xml')download(N.musicXML(state),filename()+'.musicxml','application/vnd.recordare.musicxml+xml');if(format==='project')download(JSON.stringify({...state,format:'noteflow',version:2,isDemo:false},null,2),filename()+'.noteflow','application/json');if(format==='cleaned'){if(!cleanedBuffer)throw new Error('Record or upload audio first.');download(N.wavFile(cleanedBuffer.getChannelData(0),cleanedBuffer.sampleRate),filename()+'-cleaned.wav','audio/wav')}if(format==='wav'){toast('Preparing your score audio…');const buffer=await ensureScore();download(N.wavFile(buffer.getChannelData(0),buffer.sampleRate),filename()+'.wav','audio/wav')}toast('Your download is ready.');$('export-dialog').close()}catch(e){toast(e.message)}finally{button.disabled=false}}
async function downloadApp(){try{if(location.protocol==='file:'){toast('You’re using the downloaded app. Keep this HTML file to open it again.');return}const response=await fetch('Noteflow.html');if(!response.ok)throw new Error('Download unavailable');download(await response.text(),'Noteflow.html','text/html');toast('Open Noteflow.html to use your portable app.')}catch{toast('The app download isn’t available here. Use the download supplied with your app link.')}}
async function openProject(file){if(!file)return;try{if(file.size>2*1024*1024)throw new Error('That project file is too large.');const parsed=N.validateProject(JSON.parse(await file.text()));if(N.totalBeats(parsed.notes)*60/parsed.tempo>300)throw new Error('Please use a score under 5 minutes.');snapshot();state=parsed;sourceBuffer=null;cleanedBuffer=null;sourceName='';sourceKind='restored';$('processing-report').hidden=true;invalidate();syncFields();renderScore();renderEditor();drawWave($('audio-wave'),null);persist();$('help-dialog').close();toast('Your project is open.')}catch(e){toast(e instanceof SyntaxError?'This file is not a valid Noteflow project.':e.message)}finally{$('project-file').value=''}}
$('record-tab').onclick=()=>sourceTab('record');$('upload-tab').onclick=()=>sourceTab('upload');document.querySelector('.source-tabs').addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const mode=$('record-tab').getAttribute('aria-selected')==='true'?'upload':'record';sourceTab(mode);$(mode+'-tab').focus()}});
$('record').onclick=record;$('audio-file').onchange=e=>importAudio(e.target.files[0]);$('dropzone').onclick=()=>$('audio-file').click();$('dropzone').ondragover=e=>{e.preventDefault();if(!busy)$('dropzone').classList.add('drag')};$('dropzone').ondragleave=()=>$('dropzone').classList.remove('drag');$('dropzone').ondrop=e=>{e.preventDefault();$('dropzone').classList.remove('drag');importAudio(e.dataTransfer.files[0])};
$('demo').onclick=()=>{if(busy||recording)return;snapshot();state=N.demo();sourceBuffer=null;cleanedBuffer=null;sourceName='';sourceKind='demo';$('processing-report').hidden=true;invalidate();syncFields();renderScore();renderEditor();drawWave($('audio-wave'),demoWave());persist();toast('Two-hand piano demo loaded. Press play to hear the melody and accompaniment.')};
$('title').oninput=()=>{state.title=$('title').value||'Untitled melody';state.isDemo=false;persist()};$('title').onchange=()=>renderScore();
for(const key of ['instrument','sourceInstrument','tempo','meter','grid','noise','mode','sensitivity'])$(key).onchange=()=>{if(busy||recording)return;let value=$(key).value;if(key==='tempo'){value=Math.round(Number(value));if(!Number.isFinite(value)||value<40||value>240){$(key).value=state.tempo;toast('Choose a tempo between 40 and 240 BPM.');return}if(N.totalBeats(state.notes)*60/value>300){$(key).value=state.tempo;toast('That tempo makes this score longer than 5 minutes.');return}}if(key==='grid')value=Number(value);snapshot();state[key]=value;commit();if(['grid','noise','mode','sensitivity','sourceInstrument'].includes(key))toast(sourceBuffer?'Settings updated. Select Retranscribe to apply them to this recording.':'Settings updated for your next recording.');if(key==='tempo')toast('Playback tempo updated. New recordings will use this tempo.');if(key==='instrument')toast(N.instruments[value].name+' score selected: '+N.instruments[value].description+'.')};
$('edit').onclick=()=>{const opening=$('editor').hidden;$('editor').hidden=!opening;$('edit').setAttribute('aria-expanded',String(opening));if(opening)renderEditor()};$('add-note').onclick=()=>{if(state.notes.length>=1500||seconds()+60/state.tempo>300){toast('This score is at the editing limit.');return}snapshot();state.notes.push({midi:60,pitches:[60],beats:1,tieFrom:[]});commit()};$('undo').onclick=()=>{if(!history.length)return;state=JSON.parse(history.pop());invalidate();syncFields();renderScore();renderEditor();persist()};
$('play').onclick=playScore;$('source-play').onclick=playOriginal;$('rewind').onclick=()=>{synthJob++;stopPlayback(true)};$('loop').onclick=()=>{loop=!loop;$('loop').setAttribute('aria-pressed',String(loop))};$('volume').oninput=()=>{if(window.currentGain&&audioContext)window.currentGain.gain.setTargetAtTime(Number($('volume').value)/100,audioContext.currentTime,.02)};$('seek').oninput=()=>{const wasPlaying=playing,target=Number($('seek').value)/1000*seconds();synthJob++;stopPlayback();playOffset=target;$('seek').value=String(target/seconds()*1000);$('play-time').textContent=time(target);if(wasPlaying)playScore()};
$('cancel').onclick=()=>{cancelled=true;$('progress-label').textContent='Cancelling…'};$('help').onclick=()=>{window.PPitch?.pause();$('help-dialog').showModal()};$('export').onclick=()=>$('export-dialog').showModal();document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>doExport(b.dataset.export,b));$('open-project').onclick=()=>$('project-file').click();$('project-file').onchange=e=>openProject(e.target.files[0]);$('download-app').onclick=downloadApp;
document.addEventListener('keydown',e=>{if(!$('noteflow-view').hidden&&e.code==='Space'&&!/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();playScore()}});window.addEventListener('beforeunload',()=>{stream?.getTracks().forEach(t=>t.stop())});let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{renderScore();drawWave($('audio-wave'),sourceBuffer?.getChannelData(0)||(sourceKind==='demo'?demoWave():null));if(!recording)drawWave($('live-wave'),null)},200)});
syncFields();renderScore();drawWave($('audio-wave'),sourceKind==='demo'?demoWave():null);drawWave($('live-wave'),null);persist();

$('audio-compare').onchange=()=>{stopPlayback();const buffer=$('audio-compare').value==='cleaned'?cleanedBuffer:sourceBuffer;drawWave($('audio-wave'),buffer?.getChannelData(0)||null);$('source-play').setAttribute('aria-label','Play '+$('audio-compare').value+' audio')};
$('retranscribe').onclick=async()=>{if(!sourceBuffer||busy||recording)return;try{await transcribe(sourceBuffer,sourceName,sourceKind)}catch(e){toast(e.message==='Cancelled'?'Transcription cancelled. Your previous score is safe.':e.message)}};
function workspaceTab(name){
 if(!['noteflow','ppitch'].includes(name))return false;
 if(busy||recording||requestingMic){toast('Finish recording or cancel transcription before switching tabs.');return false}
 if(!$(name+'-view').hidden)return true;
 synthJob++;stopPlayback();window.PPitch?.deactivate();
 for(const tab of ['noteflow','ppitch']){const active=tab===name;$(tab+'-view').hidden=!active;$(tab+'-tab').classList.toggle('active',active);$(tab+'-tab').setAttribute('aria-selected',String(active));$(tab+'-tab').tabIndex=active?0:-1}
 if(name==='noteflow')renderScore();else window.PPitch?.activate();return true;
}
$('noteflow-tab').onclick=()=>workspaceTab('noteflow');$('ppitch-tab').onclick=()=>workspaceTab('ppitch');
document.querySelector('.brand').onclick=e=>{e.preventDefault();workspaceTab('noteflow')};
document.querySelector('.app-tabs').onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const name=e.key==='Home'?'noteflow':e.key==='End'?'ppitch':$('noteflow-view').hidden?'noteflow':'ppitch';if(workspaceTab(name))$(name+'-tab').focus()}};

